# Generated by Django 6.0.5 on 2026-05-22 01:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agenda', '0001_initial'),
        ('clients', '0001_initial'),
        ('tenants', '0002_remove_tenant_feature_ai_insights_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='clients.client'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='professional',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professionals', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='professional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='agenda.professional'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='professional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='agenda.professional'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='scheduleblock',
            name='professional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='agenda.professional'),
        ),
        migrations.AddField(
            model_name='scheduleblock',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_blocks', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='service',
            name='professionals',
            field=models.ManyToManyField(blank=True, help_text='Vazio = todos os profissionais do tenant herdam este serviço', related_name='explicit_services', to='agenda.professional'),
        ),
        migrations.AddField(
            model_name='service',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='agenda.service'),
        ),
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together={('professional', 'weekday')},
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['tenant', 'starts_at'], name='appointment_tenant__cfc010_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['tenant', 'status'], name='appointment_tenant__9998ad_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['professional', 'starts_at'], name='appointment_profess_367c83_idx'),
        ),
    ]
