# Generated by Django 6.0.5 on 2026-05-22 21:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_initial'),
        ('clients', '0003_clientotp_clienttenantprofile_and_more'),
        ('tenants', '0002_remove_tenant_feature_ai_insights_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Ex: Pacote Mensal Corte', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('sessions', models.PositiveIntegerField(help_text='Quantidade de sessões. Ex: 4')),
                ('price', models.DecimalField(decimal_places=2, help_text='Preço do combo', max_digits=8)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='agenda.service')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Pacote',
                'verbose_name_plural': 'Pacotes',
                'db_table': 'packages',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ClientPackage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sessions_total', models.PositiveIntegerField(help_text='Cópia de package.sessions no momento da compra')),
                ('sessions_used', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('exhausted', 'Esgotado'), ('expired', 'Expirado'), ('cancelled', 'Cancelado')], default='active', max_length=20)),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Opcional — validade do pacote', null=True)),
                ('notes', models.TextField(blank=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='clients.client')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_packages', to='tenants.tenant')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_packages', to='agenda.package')),
            ],
            options={
                'verbose_name': 'Pacote do cliente',
                'db_table': 'client_packages',
                'ordering': ['-purchased_at'],
            },
        ),
    ]
