# Generated by Django 6.0.5 on 2026-05-24 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0003_package_clientpackage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'Aguardando confirmação'), ('confirmed', 'Confirmado'), ('in_comanda', 'Em atendimento'), ('completed', 'Realizado'), ('cancelled', 'Cancelado'), ('no_show', 'Não compareceu')], default='pending', max_length=20),
        ),
    ]
