# Generated by Django 6.0.5 on 2026-06-01 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0005_professional_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional',
            name='commission_frequency',
            field=models.CharField(choices=[('daily', 'Diário'), ('weekly', 'Semanal'), ('biweekly', 'Quinzenal'), ('monthly', 'Mensal')], default='monthly', max_length=10),
        ),
    ]
