# Generated by Django 6.0.5 on 2026-05-21 22:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(help_text='Subdomínio gerado automaticamente. Ex: barbearia-do-carlao', unique=True)),
                ('name', models.CharField(max_length=120, verbose_name='Nome do estabelecimento')),
                ('type', models.CharField(choices=[('barbershop', 'Barbearia'), ('salon', 'Salão de Beleza'), ('studio', 'Studio')], default='barbershop', max_length=20, verbose_name='Tipo')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail do estabelecimento')),
                ('address', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('logo_url', models.URLField(blank=True)),
                ('plan', models.CharField(choices=[('trial', 'Trial 14 dias'), ('starter', 'Starter — 1 Profissional'), ('pro', 'Pro — 2 a 5 Profissionais'), ('advanced', 'Advanced — 6 a 15 Profissionais'), ('enterprise', 'Enterprise — +15 Profissionais')], default='trial', max_length=20, verbose_name='Plano')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('trial_ends_at', models.DateTimeField(blank=True, null=True, verbose_name='Trial expira em')),
                ('email_verified', models.BooleanField(default=False, verbose_name='E-mail verificado')),
                ('setup_completed', models.BooleanField(default=False, verbose_name='Setup concluído')),
                ('feature_financial', models.BooleanField(default=False)),
                ('feature_loyalty_points', models.BooleanField(default=False)),
                ('feature_nps', models.BooleanField(default=False)),
                ('feature_return_messages', models.BooleanField(default=False)),
                ('feature_birthday_message', models.BooleanField(default=False)),
                ('feature_promo_blast', models.BooleanField(default=False)),
                ('feature_ai_insights', models.BooleanField(default=False)),
                ('feature_audio_support', models.BooleanField(default=False)),
                ('feature_custom_domain', models.BooleanField(default=False)),
                ('feature_packages', models.BooleanField(default=False)),
                ('wa_phone_number_id', models.CharField(blank=True, max_length=50)),
                ('wa_token', models.TextField(blank=True)),
                ('wa_verify_token', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Estabelecimento',
                'verbose_name_plural': 'Estabelecimentos',
                'db_table': 'tenants',
            },
        ),
        migrations.CreateModel(
            name='EmailVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_verification', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Verificação de e-mail',
                'db_table': 'email_verifications',
            },
        ),
        migrations.CreateModel(
            name='TenantBusinessHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(0, 'Segunda-feira'), (1, 'Terça-feira'), (2, 'Quarta-feira'), (3, 'Quinta-feira'), (4, 'Sexta-feira'), (5, 'Sábado'), (6, 'Domingo')])),
                ('open_time', models.TimeField(blank=True, null=True)),
                ('close_time', models.TimeField(blank=True, null=True)),
                ('is_closed', models.BooleanField(default=False)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_hours', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Horário de funcionamento',
                'verbose_name_plural': 'Horários de funcionamento',
                'db_table': 'tenant_business_hours',
                'ordering': ['weekday'],
                'unique_together': {('tenant', 'weekday')},
            },
        ),
        migrations.CreateModel(
            name='TenantUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Dono'), ('manager', 'Gerente'), ('professional', 'Profissional')], default='owner', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_users', to='tenants.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Usuário do estabelecimento',
                'verbose_name_plural': 'Usuários dos estabelecimentos',
                'db_table': 'tenant_users',
                'unique_together': {('tenant', 'user')},
            },
        ),
    ]
