# Generated by Django 6.0.5 on 2026-05-21 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='feature_ai_insights',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='feature_audio_support',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='feature_birthday_message',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='feature_custom_domain',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='feature_financial',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='feature_loyalty_points',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='feature_nps',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='feature_packages',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='feature_promo_blast',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='feature_return_messages',
        ),
        migrations.AddField(
            model_name='tenant',
            name='custom_domain',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='plan',
            field=models.CharField(choices=[('trial', 'Trial 14 dias'), ('starter', 'Starter — 1 Profissional'), ('pro', 'Pro — 2 a 5 Profissionais'), ('advanced', 'Advanced — 6 a 15 Profissionais'), ('enterprise', 'Enterprise — +15 Profissionais')], default='trial', max_length=20),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='setup_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='trial_ends_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='type',
            field=models.CharField(choices=[('barbershop', 'Barbearia'), ('salon', 'Salão de Beleza'), ('studio', 'Studio')], default='barbershop', max_length=20),
        ),
    ]
