# Generated by Django 6.0.5 on 2026-05-26 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_remove_tenant_feature_ai_insights_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantuser',
            name='title',
            field=models.CharField(blank=True, help_text='Cargo personalizado. Ex: Recepcionista, Gerente, Sócio', max_length=50),
        ),
        migrations.AlterField(
            model_name='tenantuser',
            name='role',
            field=models.CharField(choices=[('owner', 'Proprietário'), ('manager', 'Administrativo'), ('receptionist', 'Agenda completa'), ('professional', 'Profissional')], default='owner', max_length=20),
        ),
    ]
