# Generated by Django 6.0.5 on 2026-05-22 11:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agenda', '0002_initial'),
        ('tenants', '0002_remove_tenant_feature_ai_insights_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('payment_method', models.CharField(choices=[('pix', 'Pix'), ('cash', 'Dinheiro'), ('credit', 'Cartão de crédito'), ('debit', 'Cartão de débito'), ('other', 'Outro')], default='pix', max_length=20)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_entry', to='agenda.appointment')),
                ('professional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agenda.professional')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_entries', to='tenants.tenant')),
            ],
            options={
                'db_table': 'cash_entries',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'created_at'], name='cash_entrie_tenant__58298a_idx')],
            },
        ),
    ]
