# Generated by Django 6.0.5 on 2026-05-24 13:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0004_alter_appointment_status'),
        ('financial', '0001_initial'),
        ('tenants', '0002_remove_tenant_feature_ai_insights_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cashentry',
            name='commission_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='cashentry',
            name='is_manual',
            field=models.BooleanField(default=False, help_text='Lançamento manual sem agendamento'),
        ),
        migrations.CreateModel(
            name='Comanda',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('open', 'Aberta'), ('closed', 'Fechada')], default='open', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='comanda', to='agenda.appointment')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comandas', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Comanda',
                'db_table': 'comandas',
                'ordering': ['-opened_at'],
            },
        ),
        migrations.AddField(
            model_name='cashentry',
            name='comanda',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_entry', to='financial.comanda'),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('product', 'Produto'), ('extra', 'Serviço extra'), ('other', 'Outro')], default='product', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('cost_price', models.DecimalField(decimal_places=2, default=0, help_text='Preço de custo — para cálculo de margem', max_digits=8)),
                ('stock_qty', models.IntegerField(default=0, help_text='Quantidade em estoque')),
                ('stock_alert', models.IntegerField(default=5, help_text='Alerta quando estoque chegar aqui')),
                ('track_stock', models.BooleanField(default=True, help_text='False para gorjeta, desconto, etc.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'db_table': 'products',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CommandaItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(help_text='Nome do item na comanda', max_length=200)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('discount', models.DecimalField(decimal_places=2, default=0, help_text='Desconto por item em R$', max_digits=8)),
                ('is_courtesy', models.BooleanField(default=False, help_text='Cortesia — não gera comissão')),
                ('commission_pct', models.DecimalField(decimal_places=2, default=0, help_text='Copiado do profissional — editável por item', max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comanda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='financial.comanda')),
                ('product', models.ForeignKey(blank=True, help_text='Null = serviço do agendamento', null=True, on_delete=django.db.models.deletion.SET_NULL, to='financial.product')),
            ],
            options={
                'db_table': 'comanda_items',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('in', 'Entrada'), ('out', 'Saída'), ('adjust', 'Ajuste')], max_length=10)),
                ('quantity', models.IntegerField(help_text='Positivo para entrada, negativo para saída')),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('cost_price', models.DecimalField(blank=True, decimal_places=2, help_text='Preço de custo nesta movimentação (se entrada)', max_digits=8, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='financial.product')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='tenants.tenant')),
            ],
            options={
                'db_table': 'stock_movements',
                'ordering': ['-created_at'],
            },
        ),
    ]
