# Generated by Django 6.0.5 on 2026-06-01 18:01

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0002_cashentry_commission_amount_cashentry_is_manual_and_more'),
        ('tenants', '0003_tenantuser_title_alter_tenantuser_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountsPayable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('rent', 'Aluguel'), ('energy', 'Energia elétrica'), ('water', 'Água'), ('internet', 'Internet'), ('product', 'Compra de produto'), ('salary', 'Salário fixo'), ('commission', 'Comissão'), ('maintenance', 'Manutenção'), ('marketing', 'Marketing'), ('other', 'Outros')], default='other', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('due_date', models.DateField()),
                ('recurrence', models.CharField(choices=[('once', 'Única'), ('monthly', 'Mensal'), ('weekly', 'Semanal')], default='once', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('paid', 'Pago'), ('overdue', 'Em atraso')], default='pending', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('paid_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts_payable', to='tenants.tenant')),
            ],
            options={
                'ordering': ['due_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('rent', 'Aluguel'), ('energy', 'Energia elétrica'), ('water', 'Água'), ('internet', 'Internet'), ('product', 'Compra de produto'), ('salary', 'Salário fixo'), ('commission', 'Comissão'), ('maintenance', 'Manutenção'), ('marketing', 'Marketing'), ('other', 'Outros')], default='other', max_length=20)),
                ('description', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
