# Generated by Django 6.0.5 on 2026-06-02 01:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0006_professional_commission_frequency'),
        ('financial', '0003_accountspayable_expense'),
        ('tenants', '0003_tenantuser_title_alter_tenantuser_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service_name', models.CharField(max_length=200)),
                ('service_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('commission_pct', models.DecimalField(decimal_places=2, max_digits=5)),
                ('commission_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(default='pix', max_length=20)),
                ('client_name', models.CharField(blank=True, max_length=200)),
                ('client_phone', models.CharField(blank=True, max_length=30)),
                ('service_date', models.DateField()),
                ('service_time', models.TimeField()),
                ('is_paid', models.BooleanField(default=False)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commission_entries', to='agenda.appointment')),
                ('payable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commission_entries', to='financial.accountspayable')),
                ('professional', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commission_entries', to='agenda.professional')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commission_entries', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-service_date', '-service_time'],
                'indexes': [models.Index(fields=['tenant', 'professional', 'service_date'], name='financial_c_tenant__51ae1d_idx'), models.Index(fields=['tenant', 'is_paid'], name='financial_c_tenant__c00468_idx')],
            },
        ),
    ]
