# Generated by Django 6.0.5 on 2026-05-22 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('tenants', '0002_remove_tenant_feature_ai_insights_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='client',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='birthday_msg_sent_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='client',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='client',
            name='last_visit_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='loyalty_points',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='client',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='client',
            name='return_msg_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['tenant', 'phone'], name='clients_tenant__2d150d_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['tenant', 'last_visit_at'], name='clients_tenant__e8cf0b_idx'),
        ),
    ]
