# Generated by Django 6.0.5 on 2026-05-22 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_client_options_client_birthdate_and_more'),
        ('tenants', '0002_remove_tenant_feature_ai_insights_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('code', models.CharField(max_length=6)),
                ('expires_at', models.DateTimeField()),
                ('used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'client_otps',
            },
        ),
        migrations.CreateModel(
            name='ClientTenantProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loyalty_points', models.PositiveIntegerField(default=0)),
                ('last_visit_at', models.DateTimeField(blank=True, null=True)),
                ('total_visits', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'client_tenant_profiles',
            },
        ),
        migrations.RemoveIndex(
            model_name='client',
            name='clients_tenant__2d150d_idx',
        ),
        migrations.RemoveIndex(
            model_name='client',
            name='clients_tenant__e8cf0b_idx',
        ),
        migrations.AlterUniqueTogether(
            name='client',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='clientotp',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='clienttenantprofile',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_profiles', to='clients.client'),
        ),
        migrations.AddField(
            model_name='clienttenantprofile',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_profiles', to='tenants.tenant'),
        ),
        migrations.RemoveField(
            model_name='client',
            name='birthdate',
        ),
        migrations.RemoveField(
            model_name='client',
            name='birthday_msg_sent_year',
        ),
        migrations.RemoveField(
            model_name='client',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='client',
            name='last_visit_at',
        ),
        migrations.RemoveField(
            model_name='client',
            name='loyalty_points',
        ),
        migrations.RemoveField(
            model_name='client',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='client',
            name='return_msg_sent_at',
        ),
        migrations.RemoveField(
            model_name='client',
            name='tenant',
        ),
        migrations.AddIndex(
            model_name='clientotp',
            index=models.Index(fields=['tenant', 'phone', 'used'], name='client_otps_tenant__5d6aa3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='clienttenantprofile',
            unique_together={('client', 'tenant')},
        ),
    ]
