# Generated by Django 6.0.5 on 2026-05-23 21:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_clientotp_clienttenantprofile_and_more'),
        ('tenants', '0002_remove_tenant_feature_ai_insights_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clienttenantprofile',
            name='birthdate',
            field=models.DateField(blank=True, help_text='Data de aniversário', null=True),
        ),
        migrations.AddField(
            model_name='clienttenantprofile',
            name='notes',
            field=models.TextField(blank=True, help_text='Observações do barbeiro sobre o cliente'),
        ),
        migrations.CreateModel(
            name='ClientSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Ex: Assinatura Premium, Clube VIP', max_length=100)),
                ('type', models.CharField(choices=[('unlimited', 'Ilimitado'), ('limited', 'Limitado (N visitas/mês)')], default='limited', max_length=20)),
                ('visits_per_month', models.PositiveIntegerField(blank=True, help_text='Visitas permitidas por mês. Null = ilimitado.', null=True)),
                ('price', models.DecimalField(decimal_places=2, help_text='Valor mensal', max_digits=8)),
                ('visits_used', models.PositiveIntegerField(default=0, help_text='Visitas usadas no mês atual')),
                ('status', models.CharField(choices=[('active', 'Ativa'), ('paused', 'Pausada'), ('cancelled', 'Cancelada'), ('expired', 'Expirada')], default='active', max_length=20)),
                ('active_from', models.DateField()),
                ('active_until', models.DateField(blank=True, help_text='Renovado manualmente', null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='clients.client')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_subscriptions', to='tenants.tenant')),
            ],
            options={
                'db_table': 'client_subscriptions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'status'], name='client_subs_tenant__94acee_idx')],
            },
        ),
    ]
