# Generated by Django 6.0.5 on 2026-05-21 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_name', models.CharField(default='Bia', max_length=50)),
                ('welcome_message', models.TextField(default='Olá! Como posso ajudar?')),
                ('tone', models.CharField(default='friendly', max_length=20)),
                ('auto_confirm', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agent_config', to='tenants.tenant')),
            ],
            options={
                'db_table': 'agent_configs',
            },
        ),
    ]
