# Generated by Django 6.0.5 on 2026-05-22 18:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_initial'),
        ('agent', '0001_initial'),
        ('tenants', '0002_remove_tenant_feature_ai_insights_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agentconfig',
            options={'verbose_name': 'Configuração do agente'},
        ),
        migrations.AddField(
            model_name='agentconfig',
            name='escalate_keyword',
            field=models.CharField(default='humano', help_text='Palavra que transfere para atendimento humano.', max_length=50),
        ),
        migrations.AddField(
            model_name='agentconfig',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='agentconfig',
            name='max_messages_month',
            field=models.PositiveIntegerField(default=500, help_text='Limite de mensagens por mês para controle de custo.'),
        ),
        migrations.AddField(
            model_name='agentconfig',
            name='messages_this_month',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='agentconfig',
            name='wa_phone_number_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='agentconfig',
            name='wa_token',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='agentconfig',
            name='wa_verify_token',
            field=models.CharField(blank=True, help_text='Token de verificação do webhook Meta.', max_length=100),
        ),
        migrations.AlterField(
            model_name='agentconfig',
            name='tone',
            field=models.CharField(choices=[('friendly', 'Amigável e descontraído'), ('formal', 'Profissional e formal'), ('casual', 'Casual e informal')], default='friendly', max_length=20),
        ),
        migrations.AlterField(
            model_name='agentconfig',
            name='welcome_message',
            field=models.TextField(default='Olá! Como posso ajudar?', help_text='Use {agent_name} e {business_name} como variáveis.'),
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_phone', models.CharField(max_length=20)),
                ('client_name', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('active', 'Ativa'), ('escalated', 'Escalada para humano'), ('closed', 'Encerrada')], default='active', max_length=20)),
                ('history', models.JSONField(default=list)),
                ('msg_count', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_msg_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='agenda.appointment')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Conversa',
                'verbose_name_plural': 'Conversas',
                'db_table': 'conversations',
                'ordering': ['-last_msg_at'],
                'indexes': [models.Index(fields=['tenant', 'client_phone'], name='conversatio_tenant__12619b_idx'), models.Index(fields=['tenant', 'last_msg_at'], name='conversatio_tenant__d90564_idx')],
            },
        ),
    ]
